version: "3.8"

services:
  nodejs-demo-app:
    build: .
    container_name: nodejs-demo-app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - postgres-db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    depends_on:
      - nodejs-demo-app

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    depends_on:
      - prometheus

  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-devops-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: user_password123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      # - ./init-user.sql:/docker-entrypoint-initdb.d/init-user.sql
    networks:
      - app-network
  # postgres-cstomer-db:
  #   image: postgres:17-alpine
  #   container_name: postgres-customer
  #   restart: unless-stopped
  #   ports:
  #     - "5434:5432"
  #   environment:
  #     POSTGRES_DB: user_db
  #     POSTGRES_USER: user_admin
  #     POSTGRES_PASSWORD: user_password123
  #     POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  #   volumes:
  #     - postgres-customer-db-data:/var/lib/postgresql/data
  #     # - ./init-user.sql:/docker-entrypoint-initdb.d/init-user.sql
  #   networks:
  #     - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres-db

networks:
  app-network:
    driver: bridge

volumes:
  postgres-db-data:
  # postgres-customer-db-data:
